version: 0.2
# This is for flamingo production site
env:
  parameter-store:
    PROD_URL: "FLAMINGO"

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - yarn install
  build:
    commands:
      - REACT_APP_ASYNC_WORK_API=$PROD_URL yarn build

artifacts:
  base-directory: ./build
  files:
    - '**/*'

cache:
  paths:
    - './node_modules/**/*'