version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - yarn install
  build:
    commands:
      - REACT_APP_ASYNC_WORK_API=https://api.asyncworking.com/api/v1 yarn build

  
 


artifacts:
  base-directory: ./build
  files:
    - '**/*'
  

cache:
  paths:
    - './node_modules/**/*'