const formConfig = {
  nameInput: {
    label: 'Name',
    name: 'name',
    variant: 'outlined',
    margin: 'normal',
    required: true,
    fullWidth: true,
    id: 'name',
    autoFocus: true,
    autoComplete: 'name',
  },
  emailInput: {
    label: 'Email',
    name: 'email',
    variant: 'outlined',
    margin: 'normal',
    disabled: true,
    fullWidth: true,
    id: 'email',
    autoComplete: 'email',
  },
  passwordInput: {
    'data-testid': 'passwordInput',
    label: 'Password',
    variant: 'outlined',
    margin: 'normal',
    required: true,
    fullWidth: true,
    id: 'password',
    type: 'password',
    name: 'password',
    autoComplete: 'current-password',
  },
  confirmPasswordInput: {
    'data-testid': 'confirmPasswordInput',
    label: 'Confirm Password',
    variant: 'outlined',
    margin: 'normal',
    required: true,
    fullWidth: true,
    id: 'confirmPassword',
    type: 'password',
    name: 'confirmPassword',
    autoComplete: 'current-password',
  },
};

export default formConfig;
